DEMO_GRIEVANCES = [
    {
        "isDemo": True,
        "problem": "Large pothole near the school entrance on MG Road",
        "city": "Hyderabad",
        "detailedLocation": "School gate, MG Road",
        "latitude": 17.385044,
        "longitude": 78.486671,
        "department": "Municipal",
        "category": "Road Maintenance",
        "summary": "Pothole near school entrance creating vehicle and pedestrian risk.",
        "severity": "High",
        "priorityScore": 82,
        "priorityReason": "Road hazard beside a school; no immediate structural collapse.",
        "routingReason": "Road surface damage is Municipal.",
        "confidence": 0.91,
        "emergency": False,
        "emergencyReason": "No immediate life-threatening event reported.",
        "status": "Pending",
        "clusterHint": "roads-mg",
    },
    {
        "isDemo": True,
        "problem": "Garbage has been piling up for 5 days near the market",
        "city": "Hyderabad",
        "detailedLocation": "Koti market lane",
        "latitude": 17.3848,
        "longitude": 78.4861,
        "department": "Municipal",
        "category": "Sanitation",
        "summary": "Multi-day garbage accumulation.",
        "severity": "High",
        "priorityScore": 72,
        "priorityReason": "Public-health nuisance after several days, not an emergency.",
        "routingReason": "Sanitation is Municipal.",
        "confidence": 0.9,
        "emergency": False,
        "emergencyReason": "Unpleasant and unsanitary, but not an immediate life threat.",
        "status": "Pending",
        "clusterHint": "sanitation-koti",
    },
    {
        "isDemo": True,
        "problem": "Large water pipeline burst and water is flooding houses",
        "city": "Hyderabad",
        "detailedLocation": "Benz Circle service road",
        "latitude": 16.5062,
        "longitude": 80.6480,
        "department": "Water",
        "category": "Major Water Infrastructure Failure",
        "summary": "Burst main flooding homes.",
        "severity": "Critical",
        "priorityScore": 95,
        "priorityReason": "Flooding of homes is an immediate public-safety risk.",
        "routingReason": "Water infrastructure.",
        "confidence": 0.96,
        "emergency": True,
        "emergencyReason": "Major pipeline burst flooding residences.",
        "status": "Pending",
        "clusterHint": "water-benz",
    },
    {
        "isDemo": True,
        "problem": "Transformer is sparking and smoking near crowded houses",
        "city": "Hyderabad",
        "detailedLocation": "Residential lane, Benz Circle",
        "latitude": 16.5071,
        "longitude": 80.6491,
        "department": "Electricity",
        "category": "Electrical Hazard",
        "summary": "Sparking transformer beside homes.",
        "severity": "Critical",
        "priorityScore": 96,
        "priorityReason": "Electrical fire risk in a populated street.",
        "routingReason": "Electrical infrastructure.",
        "confidence": 0.97,
        "emergency": True,
        "emergencyReason": "Active sparking/smoking electrical equipment.",
        "status": "Pending",
        "clusterHint": "power-benz",
    },
    {
        "isDemo": True,
        "problem": "Person collapsed and is not responding near the bus stop",
        "city": "Hyderabad",
        "detailedLocation": "Ameerpet bus stop",
        "latitude": 17.4375,
        "longitude": 78.4483,
        "department": "Health",
        "category": "Medical Emergency",
        "summary": "Unresponsive person.",
        "severity": "Critical",
        "priorityScore": 99,
        "priorityReason": "Possible medical emergency.",
        "routingReason": "Health / EMS.",
        "confidence": 0.95,
        "emergency": True,
        "emergencyReason": "Unresponsive person.",
        "status": "Pending",
        "clusterHint": "health-ameerpet",
    },
    {
        "isDemo": True,
        "problem": "Someone is attacking people with a weapon near the market",
        "city": "Hyderabad",
        "detailedLocation": "Mozamjahi Market",
        "latitude": 17.3753,
        "longitude": 78.4744,
        "department": "Police",
        "category": "Armed Assault",
        "summary": "Reported armed violence.",
        "severity": "Critical",
        "priorityScore": 98,
        "priorityReason": "Immediate threat to life.",
        "routingReason": "Police.",
        "confidence": 0.94,
        "emergency": True,
        "emergencyReason": "Active armed threat.",
        "status": "Pending",
        "clusterHint": "police-market",
    },
    {
        "isDemo": True,
        "problem": "Building has collapsed onto the road",
        "city": "Hyderabad",
        "detailedLocation": "Old city inner road",
        "latitude": 17.3616,
        "longitude": 78.4747,
        "department": "Municipal",
        "category": "Structural Collapse",
        "summary": "Collapsed building on roadway.",
        "severity": "Critical",
        "priorityScore": 97,
        "priorityReason": "Structural collapse is a public-safety emergency.",
        "routingReason": "Municipal.",
        "confidence": 0.93,
        "emergency": True,
        "emergencyReason": "Building collapse.",
        "status": "Pending",
        "clusterHint": "collapse-oldcity",
    },
    {
        "isDemo": True,
        "problem": "Streetlight stopped working near Benz Circle",
        "city": "Vijayawada",
        "detailedLocation": "Benz Circle north side",
        "latitude": 16.5068,
        "longitude": 80.6484,
        "department": "Electricity",
        "category": "Streetlight Failure",
        "summary": "Dark streetlight.",
        "severity": "Medium",
        "priorityScore": 55,
        "priorityReason": "Visibility concern without live-wire hazard.",
        "routingReason": "Streetlight maintenance is Electricity.",
        "confidence": 0.9,
        "emergency": False,
        "emergencyReason": "No sparking or live wires reported.",
        "status": "Pending",
        "clusterHint": "light-benz",
    },
    {
        "isDemo": True,
        "problem": "Streetlight broken near Benz Circle and vehicles cannot see the turn",
        "city": "Vijayawada",
        "detailedLocation": "Benz Circle",
        "latitude": 16.5065,
        "longitude": 80.6482,
        "department": "Electricity",
        "category": "Streetlight Failure",
        "summary": "Repeat streetlight failure in the same hotspot.",
        "severity": "Medium",
        "priorityScore": 58,
        "priorityReason": "Recurring lighting failure at a busy junction.",
        "routingReason": "Electricity.",
        "confidence": 0.88,
        "emergency": False,
        "emergencyReason": "No immediate electrical fire.",
        "status": "In Progress",
        "clusterHint": "light-benz",
    },
    {
        "isDemo": True,
        "problem": "Streetlight not working near Benz Circle since last week",
        "city": "Vijayawada",
        "detailedLocation": "Benz Circle pedestrian path",
        "latitude": 16.5060,
        "longitude": 80.6478,
        "department": "Electricity",
        "category": "Streetlight Failure",
        "summary": "Third related streetlight report.",
        "severity": "Medium",
        "priorityScore": 56,
        "priorityReason": "Repeat reports increase confidence this is one civic issue.",
        "routingReason": "Electricity.",
        "confidence": 0.87,
        "emergency": False,
        "emergencyReason": "No emergency electrical hazard described.",
        "status": "Pending",
        "clusterHint": "light-benz",
    },
]
